In [60]:
import numpy as np

In [61]:
array=np.array([1,2,3])

array,array.dtype


(array([1, 2, 3]), dtype('int64'))

In [62]:
np.array(range(7))

array([0, 1, 2, 3, 4, 5, 6])

In [63]:
np.array(range(15,29))

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [64]:
np.arange(15,29)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [65]:
array = np.array([10,50,402,49,200,16 ,486])
array.min() , array.argmin()


(np.int64(10), np.int64(0))

In [66]:
array[array>20]

array([ 50, 402,  49, 200, 486])

array[array > 50]

In [67]:
array[-2:]

array([ 16, 486])

In [68]:
array[(array % 2==0) & (array > 50)]

array([402, 200, 486])

In [69]:
array[(array % 3==0) | (array < 40)]

array([ 10, 402,  16, 486])

In [74]:
array=np.arange(1923,2022)
array

array([1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933,
       1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944,
       1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955,
       1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966,
       1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977,
       1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988,
       1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,
       2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [77]:
array[(array % 400==0) | (array % 4==0) & (array % 100!=0)]

array([1924, 1928, 1932, 1936, 1940, 1944, 1948, 1952, 1956, 1960, 1964,
       1968, 1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008,
       2012, 2016, 2020])